var aNavItemData = [
	[
		{
			url:"https://www.kuazhu.com/",
			src:"images/p1.jpg",
			name:"小米9",
			price:2999,
			tag:"新品"
		},
		{
			url:"https://www.kuazhu.com/",
			src:"images/p2.jpg",
			name:"小米MX",
			price:4999,
			tag:"热卖"
		},
	],
	[
		{
			url:"https://www.kuazhu.com/",
			src:"images/p2.jpg",
			name:"小米9",
			price:2999,
			tag:"新品"
		},
		{
			url:"https://www.kuazhu.com/",
			src:"images/p2.jpg",
			name:"小米MX",
			price:4999
		},
	],
	[
		{
			url:"https://www.kuazhu.com/",
			src:"images/p1.jpg",
			name:"小米9",
			price:2999,
			tag:"新品"
		},
		{
			url:"https://www.kuazhu.com/",
			src:"images/p2.jpg",
			name:"小米MX",
			price:4999,
			tag:"热卖"
		},
		{
			url:"https://www.kuazhu.com/",
			src:"images/p1.jpg",
			name:"小米9",
			price:2999,
			tag:"新品"
		},
		{
			url:"https://www.kuazhu.com/",
			src:"images/p2.jpg",
			name:"小米MX",
			price:4999,
			tag:"热卖"
		},
		{
			url:"https://www.kuazhu.com/",
			src:"images/p1.jpg",
			name:"小米9",
			price:2999,
			tag:"新品"
		},
		{
			url:"https://www.kuazhu.com/",
			src:"images/p2.jpg",
			name:"小米MX",
			price:4999,
			tag:"热卖"
		}
	],
	[
		{
			url:"https://www.kuazhu.com/",
			src:"images/p2.jpg",
			name:"小米9",
			price:2999,
			tag:"新品"
		},
		{
			url:"https://www.kuazhu.com/",
			src:"images/p2.jpg",
			name:"小米MX",
			price:4999
		},
		{
			url:"https://www.kuazhu.com/",
			src:"images/p2.jpg",
			name:"小米9",
			price:2999,
			tag:"新品"
		},
		{
			url:"https://www.kuazhu.com/",
			src:"images/p2.jpg",
			name:"小米MX",
			price:4999
		}
	],
	[
		{
			url:"https://www.kuazhu.com/",
			src:"images/p1.jpg",
			name:"小米9",
			price:2999,
			tag:"新品"
		},
		{
			url:"https://www.kuazhu.com/",
			src:"images/p2.jpg",
			name:"小米MX",
			price:4999,
			tag:"热卖"
		},
	],
	[
		{
			url:"https://www.kuazhu.com/",
			src:"images/p2.jpg",
			name:"小米9",
			price:2999,
			tag:"新品"
		},
		{
			url:"https://www.kuazhu.com/",
			src:"images/p2.jpg",
			name:"小米MX",
			price:4999
		},
	],
	[
		{
			url:"https://www.kuazhu.com/",
			src:"images/p1.jpg",
			name:"小米9",
			price:2999,
			tag:"新品"
		},
		{
			url:"https://www.kuazhu.com/",
			src:"images/p2.jpg",
			name:"小米MX",
			price:4999,
			tag:"热卖"
		},
	],
	[
		{
			url:"https://www.kuazhu.com/",
			src:"images/p2.jpg",
			name:"小米9",
			price:2999,
			tag:"新品"
		},
		{
			url:"https://www.kuazhu.com/",
			src:"images/p2.jpg",
			name:"小米MX",
			price:4999
		},
	]
];

var aCateItemData = [
	[
		{
			url:"https://www.kuazhu.com/",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.kuazhu.com/",
			src:"images/p2.jpg",
			name:"小米MX"
		},
		{
			url:"https://www.kuazhu.com/",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.kuazhu.com/",
			src:"images/p2.jpg",
			name:"小米MX"
		},{
			url:"https://www.kuazhu.com/",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.kuazhu.com/",
			src:"images/p2.jpg",
			name:"小米MX"
		}
	],
	[
		{
			url:"https://www.kuazhu.com/",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.kuazhu.com/",
			src:"images/p1.jpg",
			name:"小米MX"
		}
	],
	[
		{
			url:"https://www.kuazhu.com/",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.kuazhu.com/",
			src:"images/p2.jpg",
			name:"小米MX"
		},
		{
			url:"https://www.kuazhu.com/",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.kuazhu.com/",
			src:"images/p2.jpg",
			name:"小米MX"
		}
	],
	[
		{
			url:"https://www.kuazhu.com/",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.kuazhu.com/",
			src:"images/p1.jpg",
			name:"小米MX"
		},
		{
			url:"https://www.kuazhu.com/",
			src:"images/p1.jpg",
			name:"小米MX"
		}
	],
	[
		{
			url:"https://www.kuazhu.com/",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.kuazhu.com/",
			src:"images/p2.jpg",
			name:"小米MX"
		},
		{
			url:"https://www.kuazhu.com/",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.kuazhu.com/",
			src:"images/p2.jpg",
			name:"小米MX"
		},{
			url:"https://www.kuazhu.com/",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.kuazhu.com/",
			src:"images/p2.jpg",
			name:"小米MX"
		}
	],
	[
		{
			url:"https://www.kuazhu.com/",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.kuazhu.com/",
			src:"images/p1.jpg",
			name:"小米MX"
		}
	],
	[
		{
			url:"https://www.kuazhu.com/",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.kuazhu.com/",
			src:"images/p2.jpg",
			name:"小米MX"
		},
		{
			url:"https://www.kuazhu.com/",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.kuazhu.com/",
			src:"images/p2.jpg",
			name:"小米MX"
		},{
			url:"https://www.kuazhu.com/",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.kuazhu.com/",
			src:"images/p2.jpg",
			name:"小米MX"
		}
	],
	[
		{
			url:"https://www.kuazhu.com/",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.kuazhu.com/",
			src:"images/p1.jpg",
			name:"小米MX"
		}
	],
	[
		{
			url:"https://www.kuazhu.com/",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.kuazhu.com/",
			src:"images/p2.jpg",
			name:"小米MX"
		},
		{
			url:"https://www.kuazhu.com/",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.kuazhu.com/",
			src:"images/p2.jpg",
			name:"小米MX"
		},{
			url:"https://www.kuazhu.com/",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.kuazhu.com/",
			src:"images/p2.jpg",
			name:"小米MX"
		}
	],
	[
		{
			url:"https://www.kuazhu.com/",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.kuazhu.com/",
			src:"images/p1.jpg",
			name:"小米MX"
		}
	]
]